---
title: "Thesis_PeerEffects"
author: "Sanjay Satish"
date: "3/9/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(flextable)
library(grid)
library(gridExtra)
library(cowplot)
library(stargazer)
library(scales)
library(pROC)
library(patchwork)
library(survminer)
library(ggsci)
library(survival)
library(foreign)
library(kableExtra)
library(ggplot2)
library(broom)
library(GGally)
library(tidyr)
library(knitr)
library(xtable)

students <- read.table("/Users/Sanscubed/Desktop/Thesis/Thesis_data/STAR_Archive/STAR_Students.tab", header = T, sep = "\t", fill = TRUE)
comparison_students <- read.table("/Users/Sanscubed/Desktop/Thesis/Thesis_data/STAR_Archive/Comparison_Students.tab", header = T, sep = "\t", fill = TRUE)
schools_spss <- read.spss("/Users/Sanscubed/Desktop/Thesis/Thesis_data/STAR_Archive/Project STAR/STAR_K-3_Schools.sav", to.data.frame=TRUE)
schools <- read.table("/Users/Sanscubed/Desktop/Thesis/Thesis_data/STAR_Archive/STAR_K-3_Schools.tab", header = T, sep = "\t", fill = TRUE)
# Converting test scores to numeric types
students$g1tmathss <- as.numeric(students$g1tmathss)
students$g1treadss <- as.numeric(students$g1treadss)
students$g1tlistss <- as.numeric(students$g1tlistss)
students$g1wordskillss <- as.numeric(students$g1wordskillss)

students$gktmathss <- as.numeric(students$gktmathss)
students$gktreadss <- as.numeric(students$gktreadss)
students$gktlistss <- as.numeric(students$gktlistss)
students$gkwordskillss <- as.numeric(students$gkwordskillss)

students$g2tmathss <- as.numeric(students$g2tmathss)
students$g3tmathss <- as.numeric(students$g3tmathss)

```

# General Peer Effects

## Data Wrangling:

```{r}
students <- students %>%
  rename(flagsgk = var6, flagsg1 = var7, flagsg2 = var8, flagsg3 = var9) 
```

## Kindergarten to First Grade

```{r}
students_peereffects_k1 <- students %>%
  filter(yearsstar != 0,  flagsgk ==1) %>%
  mutate(did_leave = case_when(flagsg1 == 0 ~ 1, flagsg1 == 1 ~ 0)) %>%
  mutate(total_math_reading_k = gktmathss + gktreadss + gktlistss + gkwordskillss, total_math_reading_1 = g1tmathss + g1treadss + g1tlistss + g1wordskillss, switched_schools = case_when(gkschid == g1schid ~ 0, gkschid != g1schid ~ 1), gkt_masters = case_when(gkthighdegree == 2 | gkthighdegree == 1 ~ 0, gkthighdegree >= 3 ~ 1), g1t_masters = case_when(g1thighdegree == 2 | g1thighdegree == 1 ~ 0, g1thighdegree >= 3 ~ 1)) 


# Prop Leavers
students_peereffects_k1 <- students_peereffects_k1 %>%
  group_by(gkschid, gktchid) %>%
  mutate(prop_leavers = (sum(did_leave)/gkclasssize)*100) %>%
  mutate(log_prop_leavers = log(prop_leavers))

# Leaver Means & Variances - Brute Force Method
students_peereffects_k1 <- students_peereffects_k1 %>%
  group_by(gkschid, gktchid) %>%
  mutate(leaver_scores = case_when(did_leave == 1 ~ total_math_reading_k, did_leave == 0 ~ 0), leaver_score_exists = case_when(did_leave == 1 & total_math_reading_k >= 0 ~ 1, did_leave == 0 ~ 0)) %>%
  mutate(leaver_mean = sum(leaver_scores, na.rm = T)/sum(leaver_score_exists, na.rm = T), leaver_variance = var(leaver_scores[leaver_scores!=0], na.rm=T))
```

```{r}
# Leave one out mean for k 
students_peereffects_k1 <- students_peereffects_k1 %>%
  group_by(gkschid, gktchid) %>%
  mutate(staying_score_exists = case_when(did_leave == 0 & total_math_reading_k >= 0 ~ 1, did_leave == 1 ~ 0)) %>%
  mutate(leave_one_out_avgk = (sum(total_math_reading_k[staying_score_exists==1], na.rm = T)-total_math_reading_k) / (sum(staying_score_exists, na.rm = T) -1)) 

# Leave one out mean for g1
# need to get average of all kids so no filtering for k cohort

leave_o1 <- students %>%
  group_by(g1schid, g1tchid) %>%
  mutate(total_math_reading_1 = g1tmathss + g1treadss + g1tlistss + g1wordskillss) %>%
  mutate(leave_one_out_avg1 = (sum(total_math_reading_1, na.rm = T)-total_math_reading_1)/(length(total_math_reading_1[!is.na(total_math_reading_1)])-1)) %>%
  select(stdntid, leave_one_out_avg1, g1tchid, g1schid)

students_peereffects_k1 <- merge(students_peereffects_k1,leave_o1,by=c("stdntid", "g1tchid", "g1schid"))

test <- students_peereffects_k1 %>%
  filter(g1schid == 257899, g1tchid == 25789906) %>%
  select(leave_one_out_avg1, flagsgk) 


# School Characteristics

```

# Regression : Kindergarten to 1st Grade

```{r}
# Regressions 
# 
#  peereffect_k1_reg_data <- students_peereffects_k1 %>%
#   filter(flagsgk == 1 & flagsg1 == 1) %>%
#   filter(gkschid == g1schid)

# peereffects_no_fe <- lm(total_math_reading_1 ~ total_math_reading_k + prop_leavers + leaver_mean + leaver_variance + prop_leavers*leaver_mean + prop_leavers*leaver_variance + as.factor(gkclasstype) + as.factor(g1classtype) + as.factor(race) + as.factor(gender) + as.factor(gkfreelunch) + as.factor(g1freelunch) + gkabsent + g1absent + as.factor(gkspeced) + as.factor(gkspecin) + as.factor(g1speced) + as.factor(g1specin) + as.factor(gktrace) + as.factor(gkt_masters) + gktyears + as.factor(g1trace) + as.factor(g1t_masters) + g1tyears + as.factor(gksurban), data = peereffect_k1_reg_data)
 

# peereffects_with_fe <- lm(fatal_rate ~ beertax + state - 1, data = Fatalities)

# peereffects_with_fe_mathscore <- lm(g1tmathss ~)

# peereffects_with_fe_readscore <- filter out students that switched schools, or left after grade 1 

```


 