---
title: "Thesis_Clustering"
author: "Sanjay Satish"
date: "3/10/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(flextable)
library(grid)
library(gridExtra)
library(cowplot)
library(stargazer)
library(scales)
library(pROC)
library(clusterSEs)
library(patchwork)
library(survminer)
library(ggsci)
library(survival)
library(plm)
library(foreign)
library(kableExtra)
library(ggplot2)
library(broom)
library(GGally)
library(tidyr)
library(knitr)
library(xtable)

cluster_data <- read.csv("/Users/Sanscubed/Desktop/Thesis/Thesis_code/Clustering/PeerEffects_K1_ClusteringData.csv") 

cluster_data <- cluster_data %>%
  distinct(stdntid, .keep_all = TRUE)
```

# Attempt at K-1 Clustering

## Data Wrangling 

```{r}
cluster_data_rownames <- cluster_data[,-2]
rownames(cluster_data_rownames) <- cluster_data[,2]

# Data for Clusters based on the following factors (incl things related to income + test scores) : Race, gender, math score, reading score, free lunch, special ed, special instruction, days absent

cluster_set_all <- cluster_data_rownames %>%
  filter(did_leave == 1) %>%
  mutate(race = as.factor(race), gkfreelunch = as.factor(gkfreelunch), gkspeced = as.factor(gkspeced), gkspecin = as.factor(gkspecin)) %>%
  select(race, gender, gktmathss, gktreadss, gktlistss, gkwordskillss, gkfreelunch, gkspeced, gkspecin, gkabsent, gkrepeat)

# Data for clusters NO INCOME/Absences/Special ED
cluster_set_noincome <- cluster_data_rownames %>%
  filter(did_leave == 1) %>%
  mutate(race = as.factor(race), gkfreelunch = as.factor(gkfreelunch), gkspeced = as.factor(gkspeced), gkspecin = as.factor(gkspecin)) %>%
  select(race, gender, gktmathss, gktreadss, gktlistss, gkwordskillss)
  
# Data for clusters NO TESTSCORES, but whether or not recommended to repeat kindergarten 
cluster_set_noscores <- cluster_data_rownames %>%
  filter(did_leave == 1) %>%
  mutate(race = as.factor(race), gkfreelunch = as.factor(gkfreelunch), gkspeced = as.factor(gkspeced), gkspecin = as.factor(gkspecin), gkrepeat = as.factor(gkrepeat)) %>%
  select(race, gender, gkfreelunch, gkspeced, gkspecin, gkabsent, gkrepeat)
```

```{r}
library(cluster)
library(factoextra)
library(readr)
library(Rtsne)

cluster_set_noincome <- na.omit(cluster_set_noincome)

gower_dist <- daisy(cluster_set_noincome, metric = "gower")
gower_mat <- as.matrix(gower_dist)

k <- 2
pam_fit <- pam(gower_dist, diss = TRUE, k)

cluster_set_noincome <- cluster_set_noincome %>%
  mutate(cluster = pam_fit$clustering)

cluster_1 <- cluster_set_noincome %>%
  filter(cluster == 1)

cluster_2 <- cluster_set_noincome %>%
  filter(cluster == 2)

```

```{r}
# C1
sum(cluster_1$race ==1,na.rm = T)/nrow(cluster_1) * 100
sum(cluster_1$race ==2,na.rm = T)/nrow(cluster_1) * 100
sum(cluster_1$race ==3,na.rm = T)/nrow(cluster_1) * 100
sum(cluster_1$race ==4,na.rm = T)/nrow(cluster_1) * 100
sum(cluster_1$race ==5,na.rm = T)/nrow(cluster_1) * 100
sum(cluster_1$race ==6,na.rm = T)/nrow(cluster_1) * 100

mean(cluster_1$gktmathss, na.rm = T)
mean(cluster_1$gktreadss, na.rm = T)
mean(cluster_1$gktlistss, na.rm = T)
mean(cluster_1$gkwordskillss, na.rm = T)

sum(cluster_1$gender ==1,na.rm = T)/nrow(cluster_1) * 100
sum(cluster_1$gkfreelunch ==1,na.rm = T)/nrow(cluster_1) * 100
sum(cluster_1$gkspeced ==1,na.rm = T)/nrow(cluster_1) * 100
sum(cluster_1$gkspecin ==1,na.rm = T)/nrow(cluster_1) * 100

mean(cluster_1$gkabsent, na.rm = T)

# C2

sum(cluster_2$race ==1,na.rm = T)/nrow(cluster_2) * 100
sum(cluster_2$race ==2,na.rm = T)/nrow(cluster_2) * 100
sum(cluster_2$race ==3,na.rm = T)/nrow(cluster_2) * 100
sum(cluster_2$race ==4,na.rm = T)/nrow(cluster_2) * 100
sum(cluster_2$race ==5,na.rm = T)/nrow(cluster_2) * 100
sum(cluster_2$race ==6,na.rm = T)/nrow(cluster_2) * 100

mean(cluster_2$gktmathss, na.rm = T)
mean(cluster_2$gktreadss, na.rm = T)
mean(cluster_2$gktlistss, na.rm = T)
mean(cluster_2$gkwordskillss, na.rm = T)

sum(cluster_2$gender ==1,na.rm = T)/nrow(cluster_2) * 100
sum(cluster_2$gkfreelunch ==1,na.rm = T)/nrow(cluster_2) * 100
sum(cluster_2$gkspeced ==1,na.rm = T)/nrow(cluster_2) * 100
sum(cluster_2$gkspecin ==1,na.rm = T)/nrow(cluster_2) * 100

mean(cluster_2$gkabsent, na.rm = T)
```



## Clustering - Mixed Clusters

### All Data

```{r}
library(cluster)
library(factoextra)
library(readr)
library(Rtsne)
set.seed(123)

# https://towardsdatascience.com/clustering-on-mixed-type-data-8bbd0a2569c3
cluster_set_all <- na.omit(cluster_set_all)

# Data 1
#' Compute Gower distance
gower_dist <- daisy(cluster_set_all, metric = "gower")
gower_mat <- as.matrix(gower_dist)

#' Print most similar students
cluster_set_all[which(gower_mat == min(gower_mat[gower_mat != min(gower_mat)]), arr.ind = TRUE)[1, ], ]

#' Print most dissimilar students
cluster_set_all[which(gower_mat == max(gower_mat[gower_mat != max(gower_mat)]), arr.ind = TRUE)[1, ], ]

# Sillouhette 
sil_width <- c(NA)
for(i in 2:8){  
  pam_fit <- pam(gower_dist, diss = TRUE, k = i)  
  sil_width[i] <- pam_fit$silinfo$avg.width  
}
plot(1:8, sil_width,
     xlab = "Number of clusters",
     ylab = "Silhouette Width", main = "Optimal Number of Clusters for Data Including All Controls")
lines(1:8, sil_width)

# Using k = 6:
k <- 6
pam_fit <- pam(gower_dist, diss = TRUE, k)
pam_results <- cluster_set_all %>%
  mutate(cluster = pam_fit$clustering) %>%
  group_by(cluster) %>%
  do(the_summary = summary(.))
pam_results$the_summary

tsne_obj <- Rtsne(gower_dist, is_distance = TRUE)
tsne_data <- tsne_obj$Y %>%
  data.frame() %>%
  setNames(c("X", "Y")) %>%
  mutate(cluster = factor(pam_fit$clustering))
cluster <- ggplot(aes(x = X, y = Y), data = tsne_data) +
  geom_point(aes(color = cluster)) + labs(title = "t-SNE Visualization of Clusters in Low-dimensional Space", subtitle = "For k=6 Clusters - All Controls")

ggsave("Clustering.pdf", plot = cluster, path = "/Users/Sanscubed/Desktop/Thesis/Thesis_figures/")

# Using k = 2:

k <- 2
pam_fit <- pam(gower_dist, diss = TRUE, k)
pam_results <- cluster_set_all %>%
  mutate(cluster = pam_fit$clustering) %>%
  group_by(cluster) %>%
  do(the_summary = summary(.))
pam_results$the_summary

tsne_obj <- Rtsne(gower_dist, is_distance = TRUE)
tsne_data <- tsne_obj$Y %>%
  data.frame() %>%
  setNames(c("X", "Y")) %>%
  mutate(cluster = factor(pam_fit$clustering))
ggplot(aes(x = X, y = Y), data = tsne_data) +
  geom_point(aes(color = cluster)) + labs(title = "t-SNE Visualization of Clusters in Low-dimensional Space", subtitle = "For k=2 Clusters - All Controls")
```

### Data w/ no Income 

```{r}
cluster_set_noincome <- na.omit(cluster_set_noincome)
# Data 1
#' Compute Gower distance
gower_dist <- daisy(cluster_set_noincome, metric = "gower")
gower_mat <- as.matrix(gower_dist)

#' Print most similar students
cluster_set_noincome[which(gower_mat == min(gower_mat[gower_mat != min(gower_mat)]), arr.ind = TRUE)[1, ], ]

#' Print most dissimilar students
cluster_set_noincome[which(gower_mat == max(gower_mat[gower_mat != max(gower_mat)]), arr.ind = TRUE)[1, ], ]

# Sillouhette 
sil_width <- c(NA)
for(i in 2:8){  
  pam_fit <- pam(gower_dist, diss = TRUE, k = i)  
  sil_width[i] <- pam_fit$silinfo$avg.width  
}
plot(1:8, sil_width,
     xlab = "Number of clusters",
     ylab = "Silhouette Width", main = "Optimal Number of Clusters for Data Without Income Controls")
lines(1:8, sil_width)

# Using k = 4:
k <- 4
pam_fit <- pam(gower_dist, diss = TRUE, k)
pam_results <- cluster_set_noincome %>%
  mutate(cluster = pam_fit$clustering) %>%
  group_by(cluster) %>%
  do(the_summary = summary(.))
pam_results$the_summary

tsne_obj <- Rtsne(gower_dist, is_distance = TRUE)
tsne_data <- tsne_obj$Y %>%
  data.frame() %>%
  setNames(c("X", "Y")) %>%
  mutate(cluster = factor(pam_fit$clustering))
ggplot(aes(x = X, y = Y), data = tsne_data) +
  geom_point(aes(color = cluster)) + labs(title = "t-SNE Visualization of Clusters in Low-dimensional Space", subtitle = "For k=4 Clusters - Data Without Income Controls")

# Using k = 2:

k <- 2
pam_fit <- pam(gower_dist, diss = TRUE, k)
pam_results <- cluster_set_noincome %>%
  mutate(cluster = pam_fit$clustering) %>%
  group_by(cluster) %>%
  do(the_summary = summary(.))
pam_results$the_summary

tsne_obj <- Rtsne(gower_dist, is_distance = TRUE)
tsne_data <- tsne_obj$Y %>%
  data.frame() %>%
  setNames(c("X", "Y")) %>%
  mutate(cluster = factor(pam_fit$clustering))
ggplot(aes(x = X, y = Y), data = tsne_data) +
  geom_point(aes(color = cluster)) + labs(title = "t-SNE Visualization of Clusters in Low-dimensional Space", subtitle = "For k=2 Clusters - Data Without Income Controls")
```

### Data w/ no Test Scores

```{r}
cluster_set_noscores <- na.omit(cluster_set_noscores)
# Data 1
#' Compute Gower distance
gower_dist <- daisy(cluster_set_noscores, metric = "gower")
gower_mat <- as.matrix(gower_dist)

#' Print most similar students
cluster_set_noscores[which(gower_mat == min(gower_mat[gower_mat != min(gower_mat)]), arr.ind = TRUE)[1, ], ]

#' Print most dissimilar students
cluster_set_noscores[which(gower_mat == max(gower_mat[gower_mat != max(gower_mat)]), arr.ind = TRUE)[1, ], ]

# Sillouhette 
sil_width <- c(NA)
for(i in 2:8){  
  pam_fit <- pam(gower_dist, diss = TRUE, k = i)  
  sil_width[i] <- pam_fit$silinfo$avg.width  
}
plot(1:8, sil_width,
     xlab = "Number of clusters",
     ylab = "Silhouette Width", main = "Optimal Number of Clusters for Data Without Achievement Controls")
lines(1:8, sil_width)

# Using k = 6:
k <- 6
pam_fit <- pam(gower_dist, diss = TRUE, k)
pam_results <- cluster_set_noscores %>%
  mutate(cluster = pam_fit$clustering) %>%
  group_by(cluster) %>%
  do(the_summary = summary(.))
pam_results$the_summary

tsne_obj <- Rtsne(gower_dist, is_distance = TRUE)
tsne_data <- tsne_obj$Y %>%
  data.frame() %>%
  setNames(c("X", "Y")) %>%
  mutate(cluster = factor(pam_fit$clustering))
ggplot(aes(x = X, y = Y), data = tsne_data) +
  geom_point(aes(color = cluster)) + labs(title = "t-SNE Visualization of Clusters in Low-dimensional Space", subtitle = "For k=6 Clusters - Data Without Achievement Controls")

# Using k = 2:

k <- 2
pam_fit <- pam(gower_dist, diss = TRUE, k)
pam_results <- cluster_set_noscores %>%
  mutate(cluster = pam_fit$clustering) %>%
  group_by(cluster) %>%
  do(the_summary = summary(.))
pam_results$the_summary

tsne_obj <- Rtsne(gower_dist, is_distance = TRUE)
tsne_data <- tsne_obj$Y %>%
  data.frame() %>%
  setNames(c("X", "Y")) %>%
  mutate(cluster = factor(pam_fit$clustering))
ggplot(aes(x = X, y = Y), data = tsne_data) +
  geom_point(aes(color = cluster)) + labs(title = "t-SNE Visualization of Clusters in Low-dimensional Space", subtitle =  "For k=2 Clusters - Data Without Achievement Controls") 
```

## Regression w/ Fixed Effects on Clusters 

```{r}
# Going to run 3 regressions: 3 each for each distance matrix with the 3 different clusters assigned, don't include any of the controls in the real regression as there's endogenity. 


```
