---
title: "Thesis_PeerEffects"
author: "Sanjay Satish"
date: "3/9/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(flextable)
library(grid)
library(gridExtra)
library(cowplot)
library(stargazer)
library(scales)
library(pROC)
library(lfe)
library(clusterSEs)
library(patchwork)
library(survminer)
library(ggsci)
library(survival)
library(plm)
library(foreign)
library(kableExtra)
library(ggplot2)
library(broom)
library(GGally)
library(tidyr)
library(knitr)
library(xtable)

students <- read.table("/Users/Sanscubed/Desktop/Thesis/Thesis_data/STAR_Archive/STAR_Students.tab", header = T, sep = "\t", fill = TRUE)
comparison_students <- read.table("/Users/Sanscubed/Desktop/Thesis/Thesis_data/STAR_Archive/Comparison_Students.tab", header = T, sep = "\t", fill = TRUE)
schools_spss <- read.spss("/Users/Sanscubed/Desktop/Thesis/Thesis_data/STAR_Archive/Project STAR/STAR_K-3_Schools.sav", to.data.frame=TRUE)
schools <- read.table("/Users/Sanscubed/Desktop/Thesis/Thesis_data/STAR_Archive/STAR_K-3_Schools.tab", header = T, sep = "\t", fill = TRUE)
# Converting test scores to numeric types
students$g1tmathss <- as.numeric(students$g1tmathss)
students$g1treadss <- as.numeric(students$g1treadss)
students$g1tlistss <- as.numeric(students$g1tlistss)
students$g1wordskillss <- as.numeric(students$g1wordskillss)

students$gktmathss <- as.numeric(students$gktmathss)
students$gktreadss <- as.numeric(students$gktreadss)
students$gktlistss <- as.numeric(students$gktlistss)
students$gkwordskillss <- as.numeric(students$gkwordskillss)

students$g2tmathss <- as.numeric(students$g2tmathss)
students$g3tmathss <- as.numeric(students$g3tmathss)

```

# General Peer Effects

## Data Wrangling:

```{r}
students <- students %>%
  rename(flagsgk = var6, flagsg1 = var7, flagsg2 = var8, flagsg3 = var9) 
```

## Kindergarten to First Grade

```{r}
students_peereffects_k1 <- students %>%
  filter(yearsstar != 0,  flagsgk ==1) %>%
  mutate(did_leave = case_when(flagsg1 == 0 ~ 1, flagsg1 == 1 ~ 0)) %>%
  mutate(total_math_reading_k = gktmathss + gktreadss + gktlistss + gkwordskillss, total_math_reading_1 = g1tmathss + g1treadss + g1tlistss + g1wordskillss, switched_schools = case_when(gkschid == g1schid ~ 0, gkschid != g1schid ~ 1), gkt_masters = case_when(gkthighdegree == 2 | gkthighdegree == 1 ~ 0, gkthighdegree >= 3 ~ 1), g1t_masters = case_when(g1thighdegree == 2 | g1thighdegree == 1 ~ 0, g1thighdegree >= 3 ~ 1)) 


# Prop Leavers
students_peereffects_k1 <- students_peereffects_k1 %>%
  group_by(gkschid, gktchid) %>%
  mutate(prop_leavers = (sum(did_leave)/gkclasssize)*100) %>%
  mutate(log_prop_leavers = log(prop_leavers))

# Leaver Means & Variances - Brute Force Method
students_peereffects_k1 <- students_peereffects_k1 %>%
  group_by(gkschid, gktchid) %>%
  mutate(leaver_scores = case_when(did_leave == 1 ~ total_math_reading_k, did_leave == 0 ~ 0), leaver_score_exists = case_when(did_leave == 1 & total_math_reading_k >= 0 ~ 1, did_leave == 0 ~ 0)) %>%
  mutate(leaver_mean = sum(leaver_scores, na.rm = T)/sum(leaver_score_exists, na.rm = T), leaver_variance = var(leaver_scores[leaver_scores!=0], na.rm=T))
```

```{r}
# Leave one out mean for k 
students_peereffects_k1 <- students_peereffects_k1 %>%
  group_by(gkschid, gktchid) %>%
  mutate(staying_score_exists = case_when(did_leave == 0 & total_math_reading_k >= 0 ~ 1, did_leave == 1 ~ 0)) %>%
  mutate(leave_one_out_avgk = (sum(total_math_reading_k[staying_score_exists==1], na.rm = T)-total_math_reading_k) / (sum(staying_score_exists, na.rm = T) -1)) 

# Leave one out mean for g1
# need to get average of all kids so no filtering for k cohort

leave_o1 <- students %>%
  group_by(g1schid, g1tchid) %>%
  mutate(total_math_reading_1 = g1tmathss + g1treadss + g1tlistss + g1wordskillss) %>%
  mutate(leave_one_out_avg1 = (sum(total_math_reading_1, na.rm = T)-total_math_reading_1)/(length(total_math_reading_1[!is.na(total_math_reading_1)])-1)) %>%
  select(stdntid, leave_one_out_avg1, g1tchid, g1schid)

students_peereffects_k1 <- merge(students_peereffects_k1,leave_o1,by=c("stdntid", "g1tchid", "g1schid"))

# School Characteristics
schools_1 <- schools %>%
  select(schid, var4, var21, var22) %>%
  rename(g1schid = "schid", flag_s1 = "var4", g1_fl = "var21", g1_bus = "var22") %>%
  filter(flag_s1 == 1)

schools_k <- schools %>%
  select(schid, var2, var3, var9, var10) %>%
  rename(gkschid = "schid", grdrange = "var2", flag_sk = "var3", gk_fl = "var9", gk_bus = "var10") %>%
  filter(flag_sk == 1) 
  
students_peereffects_k1 <- merge(students_peereffects_k1,schools_k,by="gkschid")
  
write.csv(students_peereffects_k1,"/Users/Sanscubed/Desktop/Thesis/Thesis_code/Clustering/PeerEffects_K1_ClusteringData.csv", row.names = FALSE)

students_peereffects_k1 <- merge(students_peereffects_k1,schools_1,by="g1schid")
```

# EDA Plots Income & Ability:

```{r}

fl_test_k <- ggplot(data=students_peereffects_k1[!(is.na(students_peereffects_k1$gkfreelunch)), ], aes(x=total_math_reading_k, group=as.factor(gkfreelunch), fill=as.factor(gkfreelunch))) +
    geom_density(adjust=1.5, alpha=.4) + labs(title = "Distribution of Total Kindergarten \nTest Scores by Free Lunch Status") + xlab("Total Kindergarten Test Score") + ylab("Density") + theme_pubr() + scale_fill_nejm(name = "Free Lunch Status in Kindergarten", labels = c("Recieves Free Lunch", "Non Free Lunch")) + xlim(1500, 2750) + theme(plot.title = element_text(size=13))

fl_test_1 <- ggplot(data=students_peereffects_k1[!(is.na(students_peereffects_k1$g1freelunch)), ], aes(x=total_math_reading_1, group=as.factor(g1freelunch), fill=as.factor(g1freelunch))) +
    geom_density(adjust=1.5, alpha=.4) + labs(title = "Distribution of Total First Grade \nTest Scores by Free Lunch Status") + xlab("Total First Grade Test Score") + ylab("Density") + theme_pubr() + scale_fill_nejm(name = "Free Lunch Status in First Grade", labels = c("Recieves Free Lunch", "Non Free Lunch")) + xlim(1500, 2750) + theme(plot.title = element_text(size=13))

arranged <- ggarrange(fl_test_k, fl_test_1, ncol=2, nrow=1, common.legend = TRUE, legend="bottom")
ggsave("FL_Ability.pdf", plot = arranged, path = "/Users/Sanscubed/Desktop/Thesis/Thesis_figures/")
```

# Regression : Kindergarten to 1st Grade

```{r}
# Regression Data

peereffect_k1_reg_data <- students_peereffects_k1 %>%
  filter(flagsgk == 1 & flagsg1 == 1) %>%
  filter(gkschid == g1schid) %>%
  filter(gkfreelunch == g1freelunch) %>%
  mutate(is_smallk = case_when(gkclasstype == 1 ~ 1, TRUE ~ 0), is_regulark = case_when(gkclasstype == 2 ~ 1, TRUE ~ 0), is_rak = case_when(gkclasstype == 3 ~ 1, TRUE ~ 0), is_small1 = case_when(g1classtype == 1 ~ 1, TRUE ~ 0), is_regular1 = case_when(g1classtype == 2 ~ 1, TRUE ~ 0), is_ra1 = case_when(g1classtype == 3 ~ 1, TRUE ~ 0)) 
  
peereffects_no_fe <- felm(total_math_reading_1 ~ total_math_reading_k + prop_leavers + leaver_mean + leaver_variance + prop_leavers * leaver_mean + prop_leavers * leaver_variance + is_smallk + is_regulark + is_rak + is_small1 + is_regular1 + is_ra1 + leave_one_out_avgk + as.factor(race) + as.factor(gender) + as.factor(gkfreelunch) + as.factor(g1freelunch) + gkabsent + g1absent + as.factor(gkspeced) + as.factor(gkspecin) + as.factor(g1speced) + as.factor(g1specin) + as.factor(gktrace) + as.factor(gkt_masters) + gktyears + as.factor(g1trace) + as.factor(g1t_masters) + g1tyears + as.factor(gksurban) + as.factor(grdrange) + gk_fl + gk_bus + g1_fl + g1_bus| 0 | 0 |gktchid, data = peereffect_k1_reg_data)
 

peereffects_with_fe <- plm(total_math_reading_1 ~ total_math_reading_k + prop_leavers + leaver_mean + leaver_variance + prop_leavers * leaver_mean + prop_leavers * leaver_variance + as.factor(gkclasstype) + as.factor(g1classtype) + leave_one_out_avgk + leave_one_out_avg1 + as.factor(race) + as.factor(gender) + as.factor(gkfreelunch) + as.factor(g1freelunch) + gkabsent + g1absent + as.factor(gkspeced) + as.factor(gkspecin) + as.factor(g1speced) + as.factor(g1specin) + as.factor(gktrace) + as.factor(gkt_masters) + gktyears + as.factor(g1trace) + as.factor(g1t_masters) + g1tyears, data = peereffect_k1_reg_data,
                    index = c("gkschid", "g1schid"), 
                    model = "within", effect="twoways")

peereffects_with_fe_mathscore <- plm(g1tmathss ~ total_math_reading_k + prop_leavers + leaver_mean + leaver_variance + prop_leavers * leaver_mean + prop_leavers * leaver_variance + as.factor(gkclasstype) + as.factor(g1classtype) + leave_one_out_avgk + leave_one_out_avg1 + as.factor(race) + as.factor(gender) + as.factor(gkfreelunch) + as.factor(g1freelunch) + gkabsent + g1absent + as.factor(gkspeced) + as.factor(gkspecin) + as.factor(g1speced) + as.factor(g1specin) + as.factor(gktrace) + as.factor(gkt_masters) + gktyears + as.factor(g1trace) + as.factor(g1t_masters) + g1tyears + as.factor(gksurban) + as.factor(grdrange) + gk_fl + gk_bus + g1_fl + g1_bus, data = peereffect_k1_reg_data,
                    index = c("gkschid", "g1schid"), 
                    model = "within", effect="twoways")

peereffects_with_fe_readscore <- plm(g1treadss ~ total_math_reading_k + prop_leavers + leaver_mean + leaver_variance + prop_leavers*leaver_mean + prop_leavers*leaver_variance + as.factor(gkclasstype) + as.factor(g1classtype) + leave_one_out_avgk + leave_one_out_avg1 + as.factor(race) + as.factor(gender) + as.factor(gkfreelunch) + as.factor(g1freelunch) + gkabsent + g1absent + as.factor(gkspeced) + as.factor(gkspecin) + as.factor(g1speced) + as.factor(g1specin) + as.factor(gktrace) + as.factor(gkt_masters) + gktyears + as.factor(g1trace) + as.factor(g1t_masters) + g1tyears + as.factor(gksurban) + as.factor(grdrange) + gk_fl + gk_bus + g1_fl + g1_bus, data = peereffect_k1_reg_data,
                    index = c("gkschid", "g1schid"), 
                    model = "within", effect="twoways")

```

# More EDA:

```{r}
ggplot(peereffect_k1_reg_data, aes(x=total_math_reading_1, y=leaver_mean)) +
  geom_point() +
  geom_smooth(method=lm , color="red", fill="#69b3a2", se=TRUE) + labs(title = "Own Test Score vs. Leaver Mean Test Score")

ggplot(peereffect_k1_reg_data, aes(x=total_math_reading_1, y=leave_one_out_avg1)) +
  geom_point() +
  geom_smooth(method=lm , color="red", fill="#69b3a2", se=TRUE) + labs(title = "Own Test Score vs. Peer Mean Test Score")

ggplot(data=peereffect_k1_reg_data[!(is.na(peereffect_k1_reg_data$g1freelunch)), ], aes(x=leave_one_out_avgk, group=as.factor(g1freelunch), fill=as.factor(g1freelunch))) +
    geom_density(adjust=1.5, alpha=.4) + labs(title = "Distribution of Leaver Mean Scores by Free Lunch Status") + xlab("Total First Grade Test Score") + ylab("Density") + theme_pubr() + scale_fill_nejm(name = "Free Lunch Status in First Grade", labels = c("Recieves Free Lunch", "Non Free Lunch")) + xlim(1500, 2750) + theme(plot.title = element_text(size=13))
```


# Regression Tables 

```{r}
compressed_table <- stargazer(peereffects_no_fe, peereffects_with_fe, peereffects_with_fe_mathscore, peereffects_with_fe_readscore, title="Coefficient-Level Estimates for Peer Effects among Kindergarten Entry Cohort", align=TRUE, type = 'latex', header = FALSE, single.row = FALSE, column.sep.width = "3pt", font.size = "small", omit.stat=c("f"), model.names = FALSE, notes.align = "l", omit = c("gender", "race", "gktyears", "gkabsent", "grdrange", "gk_fl", "gk_bus", "gkfreelunch", "g1absent", "gkspeced", "gkspecin", 'g1speced', "g1specin", "gktrace", "gkt_masters", "g1trace",  "g1t_masters",  "g1tyears",  "gksurban", "g1_fl", "g1_bus"), add.lines=list(c("Fixed Effects", "No", "Yes", "Yes", "Yes")))

```

# Diagnostics 

``` {r}
# Create Robustness model for measuring levergae
fe_model_robust <- lm(total_math_reading_1 ~ total_math_reading_k + prop_leavers + leaver_mean + leaver_variance + prop_leavers * leaver_mean + prop_leavers * leaver_variance + as.factor(gkclasstype) + as.factor(g1classtype) + leave_one_out_avgk + leave_one_out_avg1 + as.factor(race) + as.factor(gender) + as.factor(gkfreelunch) + as.factor(g1freelunch) + gkabsent + g1absent + as.factor(gkspeced) + as.factor(gkspecin) + as.factor(g1speced) + as.factor(g1specin) + as.factor(gktrace) + as.factor(gkt_masters) + gktyears + as.factor(g1trace) + as.factor(g1t_masters) + g1tyears + as.factor(gksurban) + as.factor(grdrange) + gk_fl + gk_bus + g1_fl + g1_bus + gkschid - 1, data = peereffect_k1_reg_data)

# Augment dataset for plotting leverage and residuals 
panel_output <- augment(fe_model_robust) %>%
  mutate(obs_num = row_number())

# Add residuals and standardize
panel_output <- panel_output %>%
  mutate(predicted = predict.lm(fe_model_robust), resid = residuals(fe_model_robust))

# Create Leverage threshold
leverage_threshold <- 2*(32+1)/(nrow(panel_output))

# Plot and save Figure 4
ggplot(data = panel_output ,aes(x = obs_num, y = .hat)) + 
  geom_point(alpha = 0.7) + 
  geom_hline(yintercept = leverage_threshold,color = "red")+
  labs(x = "Observation Number", y = "Leverage",title = "Scatterplot of Observations with Respect to Leverage for Fixed Effects Model", caption = "Leverage Threshold in Red")


# Plot Figure 5 and save to device
ggplot(data = panel_output, aes(x = obs_num, y = .cooksd)) + 
  geom_point(alpha = 0.7) + 
  geom_hline(yintercept=1,color = "red")+
  labs(x= "Observation Number",y = "Cook's Distance",title = "Scatterplot of Observations with Respect to Cook's Distance for Fixed Effects Model", caption = "Cook's Distance Threshold in Red") + 
  geom_text(aes(label = ifelse(.hat>1,as.character(obs_num),"")))


# Plot Figure 6 and save to device
ggplot(data = panel_output, aes(x = .fitted,y = .std.resid)) +
  geom_point(alpha = 0.7) + 
  geom_hline(yintercept = 0,color = "red") +
  geom_hline(yintercept = -2,color = "red",linetype = "dotted") +
  geom_hline(yintercept = 2,color = "red",linetype = "dotted") +
  labs(x ="Predicted Value",y ="Standardized Residuals",title = "Standardized Residuals (Normal ~ (0,1)) vs. Predicted Values for ", caption = "Observation Numbers Labeled for those Outside +/- 2 Standard Deviations From the Mean") +
  geom_text(aes(label = ifelse(abs(.std.resid) >2,as.character(obs_num),"")), nudge_x = 0.08)


# Pull Observations outside +/- 2 SD of residuals
highresiduals <- panel_output %>% filter(abs(.std.resid) > 2)

# Table 4

# refitting model
refit_data <- peereffect_k1_reg_data[-c(6,    14,   116,  137,  169,  185,  361,  362,  363,  370,  376,  378,  380,  399,  466,  495,  535,  538,  576,  600,  750, 
763,  850,  869,  923,  925,  958,  998,  1002, 1020, 1027, 1036, 1041, 1073, 1255, 1266, 1395, 1609, 1631, 1692, 1701, 1713,
1862, 1936, 1982, 1989, 1995, 1999, 2013, 2029, 2163, 2269, 2294, 2295, 2297, 2457, 2486, 2555, 2558, 2626, 2671, 2687, 2690,
 2706, 2716, 2735, 2811, 2847, 2914, 2920, 2962, 2981, 3035, 3149, 3151, 3229, 3244, 3246, 3248, 3258, 3264, 3303, 3351, 3354,
 3361, 3377, 3393, 3403, 3425, 3434, 3452, 3460, 3481, 3483, 3636, 3670, 3679, 3698, 3720, 3743, 3829, 3843, 3859, 3860, 3949,
4021, 4029, 4054, 4060, 4143, 4175, 4228, 4238), ]

refit_with_fe <- plm(total_math_reading_1 ~ total_math_reading_k + prop_leavers + leaver_mean + leaver_variance + prop_leavers * leaver_mean + prop_leavers * leaver_variance + as.factor(gkclasstype) + as.factor(g1classtype) + leave_one_out_avgk + leave_one_out_avg1 + as.factor(race) + as.factor(gender) + as.factor(gkfreelunch) + as.factor(g1freelunch) + gkabsent + g1absent + as.factor(gkspeced) + as.factor(gkspecin) + as.factor(g1speced) + as.factor(g1specin) + as.factor(gktrace) + as.factor(gkt_masters) + gktyears + as.factor(g1trace) + as.factor(g1t_masters) + g1tyears + as.factor(gksurban) + as.factor(grdrange) + gk_fl + gk_bus + g1_fl + g1_bus, data = refit_data,
                    index = c("gkschid"), 
                    model = "within")

```

 